version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  labels:
  - Automatic
  ignore:
  - dependency-name: webpack
    versions:
    - 5.31.1
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.2.3
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  labels:
  - Automatic
