version: '{build}-{branch}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
clone_depth: 10
environment:
  NODE_JS_VERSION: lts
install:
- pwsh: >-
    Set-StrictMode -Version Latest

    $ErrorActionPreference = 'Stop'

    $ProgressPreference = 'SilentlyContinue'


    git submodule sync --recursive


    if ($LastExitCode -ne 0) {
        throw "Last command failed."
    }


    git submodule update --init --recursive


    if ($LastExitCode -ne 0) {
        throw "Last command failed."
    }
- ps: Install-Product node "$env:NODE_JS_VERSION"
build_script:
- pwsh: >-
    Set-StrictMode -Version Latest

    $ErrorActionPreference = 'Stop'

    $ProgressPreference = 'SilentlyContinue'


    npm ci --no-progress


    if ($LastExitCode -ne 0) {
        throw "Last command failed."
    }


    npm run-script build --no-progress


    if ($LastExitCode -ne 0) {
        throw "Last command failed."
    }
after_test:
- pwsh: >-
    Set-StrictMode -Version Latest

    $ErrorActionPreference = 'Stop'

    $ProgressPreference = 'SilentlyContinue'


    7z a -bd -slp -tzip -mm=Deflate -mx=1 'out\ASF-WebConfigGenerator.zip' "$env:APPVEYOR_BUILD_FOLDER\docs\*"


    if ($LastExitCode -ne 0) {
        throw "Last command failed."
    }


    # TODO: Change me to Push-AppveyorArtifact once https://github.com/appveyor/ci/issues/2183 is fixed

    appveyor PushArtifact 'out\ASF-WebConfigGenerator.zip' -FileName 'ASF-WebConfigGenerator.zip' -DeploymentName 'ASF-WebConfigGenerator.zip'
deploy: off
notifications:
- provider: Webhook
  url:
    secure: i/og7KzkpbcWcKoUubrLH+KB6bkfqA55FHUlGxLepLmgZNQeNMiMoAFICOFY795fFrFfUNUKqwk7ApXE6HUyWMoiijLj7G/JBLTPkBiTCu8fZMTMqwQm6FiHB3+/0h0C+ukcrBEqnXYSQUh6znpKqJSTrIfXUQ7ftNuC966kBAw=
  method: POST
  body: >-
    {
    	"avatar_url": "https://www.appveyor.com/assets/img/appveyor-logo-256.png",
    	"username": "AppVeyor",
    	"content": "[{{projectName}}:{{branch}}] {{commitMessage}} by {{commitAuthor}} ({{commitId}}) | **{{status}}** on {{buildUrl}}"
    }
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
