name: ASF-WebConfigGenerator-lock-threads

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Lock inactive threads
        uses: dessant/lock-threads@v2.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-lock-inactive-days: 30
          pr-lock-inactive-days: 30
